### ISSUE TITLE
Much guides, many info!

### ISSUE THREAD

**Issue by tadaszelvys** [Ragazzo/yii2-ddd#7]
:P

**Comment by Ragazzo** [comment]
@tadaszelvys current docs are under development on private repo on `bitbucket` will be published to github

**Comment by tadaszelvys** [comment]
Nothing in particular, just encouraging to add some info, should be a very good and helpful read. Any chance of sharing private docs for sneak peak ?

**Comment by Ragazzo** [comment]
> just encouraging to add some info, should be a very good and helpful read.

feel free to open new issues about what you want to see in the guide or about paricular examples you want to add 

>Any chance of sharing private docs for sneak peak ?

since you said you are in DDD i skiped Chapter 1 and Introduction, there are currently only chapters about DDD Strategic, of course there will be chapters about DDD Tactical 

- https://gist.github.com/Ragazzo/830cc195b54fde87268d
- https://gist.github.com/Ragazzo/27a02ab5c814db4bad0f
- https://gist.github.com/Ragazzo/f373ad6bf7744783b0cc

**Comment by alanwillms** [comment]
Can't wait to read how you propose to solve the DDD Repository vs ActiveRecord pattern issue.

**Comment by Ragazzo** [comment]
I skiped it and changed my mind to use Repository implementation by Doctrine2, since it gives you more Persistence Ignorance and solves various Impedance Mismatch problems like inheritance or simple DateTime usage. Although if talking about PI you can implement your own Repository via AR, but it will be very hard since transaction should be controlled by application and not the entity itslef. AR is a godd way for [Table Model](http://martinfowler.com/eaaCatalog/tableModule.html)
